# Created by Jekyll Writer
title: 理学院大数据课题小组
author: 李厚峰
description: 课题小组所用，测试阶段
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: Genesis2011
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /Learn-BigData
